Module5 task1
htmlacademy-ecmascript/178784-cinemaddict-18 pull request #6
Opened 2022-09-05 15:25 UTC by nvrrus

2022-09-07 09:28 UTC, andreevsm requested changes

2022-09-07 09:28 UTC, andreevsm commented on src/constants.module.js
> +  IMG_TAG: "IMG",
Надо исправить замечания от Github Actions)

2022-09-07 09:28 UTC, andreevsm commented on src/model/films.js
> +    film.isInWatchlist = !film.isInWatchlist;
Давай лучше воспользуемся иммутабельным подходом:
1. Находим фильм и его индекс в this.#films
2. Создаем новый объект на основе найденного фильма. Добавляем свойство, значение которого хотим изменить
3. Вставляем этот фильм в массив `this.#films`, учитывая порядок (тут нужен будет индекс из п. 1)

2022-09-07 09:28 UTC, andreevsm commented on src/presenter/film-popup-presenter.js
> +    if (!this.#filmPopupView) {
Советую перед и после условиями делать отступ, чтобы визуально было понятнее)

2022-09-07 09:28 UTC, andreevsm commented on src/presenter/films-presenter.js
> +   * @param {Object} film
Точно нужен такой комментарий? Дело в том, что он не несет никакой смысловой нагрузки: из названия параметра уже понятно, что ожидается объект фильма)

2022-09-07 09:28 UTC, andreevsm commented on src/presenter/filters-presenter.js
> +        if (this.#filtersView) {
Кажется, в этом файле поехало форматирование: по 4 пробела почему-то

2022-09-07 09:28 UTC, andreevsm commented on src/presenter/filters-presenter.js
> +}
Добавь enter в конце файла)

2022-09-07 09:28 UTC, andreevsm commented on src/template/film-card-temlate.js
> +    case 'watchlist':
Давай воспользуемся константами)

2022-09-07 09:28 UTC, andreevsm commented on src/template/film-popup-template.js
> +    case 'watchlist':
И тут константы

2022-09-07 09:28 UTC, andreevsm commented on src/view/film-list-view.js
> +  #getFilmId = (targetElement) => {
Я бы предложил вынести этот метод за пределы класса, так как он не работает со свойствами класса)

2022-09-07 09:28 UTC, andreevsm commented on src/presenter/film-popup-presenter.js
> +  /** @type {FilmPopupView} */
Так а где презентер для фильма согласно первому заданию?)

2022-09-07 09:28 UTC, andreevsm commented on src/presenter/film-popup-presenter.js
> +      const newfilmPopupView = new FilmPopupView(film, filmComments);
Так же если кликнуть на карточку при уже открытом попапе, то попап изменится
Согласно заданию пользователь не может кликать на карточки, если попап уже открыт)

2022-09-08 04:20 UTC, nvrrus commented on src/constants.module.js
> +  IMG_TAG: "IMG",
поправил, спасибо, eslint оказывается не работал)

2022-09-08 04:24 UTC, nvrrus commented on src/model/films.js
> +    film.isInWatchlist = !film.isInWatchlist;
А для чего так делать?

2022-09-08 05:09 UTC, nvrrus commented on src/presenter/film-popup-presenter.js
> +  /** @type {FilmPopupView} */
film-popup-presenter - это презентер для фильма

2022-09-08 05:54 UTC, nvrrus commented on src/presenter/film-popup-presenter.js
> +      const newfilmPopupView = new FilmPopupView(film, filmComments);
поправил, вообще логично, но не нахожу такое в ТЗ

2022-09-08 05:57 UTC, nvrrus commented on src/presenter/filters-presenter.js
> +        if (this.#filtersView) {
на новом компе забыл плагины поставить eslint, editorconfig
поправил во всех файлах, спасибо

2022-09-09 07:08 UTC, nvrrus commented on src/presenter/film-popup-presenter.js
> +  /** @type {FilmPopupView} */
еще разбил на презентеры для списков

2022-09-09 11:08 UTC, merged